apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: prune-app
  namespace: argocd
spec: 
  destination: 
    namespace: prune
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: guestbook-with-sub-directories
    repoURL: "https://github.com/raghib1992/argocd-example-apps.git"
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated:
      prune: true
    syncOptions:
      - CreateNamespace=true
