apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: no-prune-app
  namespace: argocd
spec: 
  destination: 
    namespace: no-prune-app
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: sync-options/no-prune
    repoURL: "https://github.com/raghib1992/argocd-example-apps.git"
    targetRevision: master
    directory:
      recurse: true
  syncPolicy:
    automated: {}
    syncOptions:
      - CreateNamespace=true
