apiVersion: v1
kind: PersistentVolume
metadata:
  name: host-pv
spec:
  capacity:
    storage: 1Gi
  volumeMode: Filesystem
  storageClassName: hostpath
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: C:\Users\10728749\raghib\temp
    type: DirectoryOrCreate
