---
# ConfigMap
apiVersion: v1
kind: ConfigMap
metadata:
    name: demo-config
data:
    channel.name: Tammana
    channel.url: diksha
      # file-like keys
    game.properties: |
        enemy.types=aliens,monsters
        player.maximum-lives=5    
    user-interface.properties: |
        color.good=purple
        color.bad=yellow
        allow.textmode=true

---
apiVersion:
kind:
metadata:
spec:
    volumes:
        - name: demo-volume
          ConfigMap:
            name: demo-config
            items:
                - key:
                  path:
    containers:
        - name:
          image:
          ports:
          - containerPort:
          commands:
          args:
          env:
            - name: 
              fromValue:
                configMapKeyRef:
                    name: demo-config
                    key: channel.name
          volumeMounts:
            - name: demo-volume
              mountPath: "/mydata"
              readOnly: true
---
# Resource Quotas
## Create namespace
## kubectl create ns quota-demo-ns

## Create Resource Quota
apiVersion: v1
kind: ResourceQuota
metadata:
  name: quota-demo1
  namespace: quota-demo-ns
spec:
  hard:
    pods: "2"
    configmaps: "1"
---
apiVersion: v1
kind: ResourceQuota
metadata:
  name: q
  namespace: a
spec:
  hard:
    limits.memory: "500Mi"
---
# Resource Limit Range
apiVersion: v1
kind: LimitRange
metadata:
  name: lr
  namespace: a
spec:
  limits:
  - default:
      memory: 300Mi
    defaultRequest:
      memory: 50Mi
    type: Container
---
# resource quota with request limit
apiVersion: v1
kind: ResourceQuota
metadata:
  name: q
  namespace: a
spec:
  hard:
    limits.memory: "500Mi"
    requests.memory: "100Mi"
---


apiVersion: v1
kind: ResourceQuota
metadata:
  name: test-app-rq
  namespace: test
spec:
  hard:
    limits.memory:
    requests.memory:
    pods:
    configmaps:

---
apiVersion: v1
kind: LimitRange
metadata:
  name: lr
  namespace: a
spec:
  limits:
    default:
      memory: "300Mi"
    defaultRequest:
      memroy: "200Mi"
    type: Container