apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "helmbasics.resourceName" . }}
  labels:
{{- include "helmbasics.labels" . }}
spec:
  replicas: 2
  selector:
    matchLabels:
{{- include "helmbasics.labels" . | indent 2 }}
  template:
    metadata:
      labels:
{{- include "helmbasics.labels" . | indent 4 }}
    spec:
      containers:
      - name: nginx
        image: ghcr.io/stacksimplify/kubenginx:4.0.0
        ports:
        - containerPort: 80
