apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      name: frontend-pod
      labels: 
        app: frontend
    spec:
      containers:
        - name: frontend
          image: raghib1992/nodejs-frontend

