apiVersion: apps/v1
kind: Deployment
metadata:
  name: tasks-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: tasks
  template:
    metadata:
      name: tasks-pod
      labels: 
        app: tasks
    spec:
      containers:
        - name: tasks
          image: raghib1992/nodejs-tasks
          env:
            - name: AUTH_ADDRESS
              value: "auth-service.default"
            - name: TASKS_FOLDER
              value: tasks

