apiVersion: apps/v1
kind: Deployment
metadata:
  name: users-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: users
  template:
    metadata:
      name: users-pod
      labels: 
        app: users
    spec:
      containers:
        - name: users
          image: raghib1992/nodejs-users
          env:
            - name: AUTH_ADDRESS
              value: auth-service

