apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: uzmabook
  namespace: argocd
spec: 
  destination: 
    namespace: uzma
    server: "https://kubernetes.default.svc"
  project: dev-project
  source: 
    path: guestbook
    repoURL: "https://github.com/raghib1992/argocd-example-apps.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true