apiVersion: v1
kind: Pod
metadata:
  name: env-test
spec:
  containers:
    - name: test-container
      image: registry.k8s.io/busybox
      command: [ "/bin/sh", "-c", "env" ]
      env:
        - name: SPECIAL_KEY_VALUE
          valueFrom:
            configMapKeyRef:
              name: special-config
              key: special.how
  restartPolicy: Never