apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: dev-project
  namespace: argocd
spec:
  description: Dev project
  sourceRepos:
  - 'https://github.com/raghib1992/argocd-example-apps.git'

  destinations:
  - namespace: 'dev'
    server: 'https://kubernetes.default.svc'

  clusterResourceWhitelist:
  - group: '*'
    kind: '*'

  namespaceResourceWhitelist:
  - group: '*'
    kind: '*'
  
  roles:
  - name: dev-role
    description: Dev Project
    policies:
    - p, proj:dev-project:dev-role , applications, create,list,get, dev-project/*, allow
