apiVersion: v1
kind: Service
metadata:
  name: nlb-usermgmt-restapp
  labels: 
    app: usermgmt-restapp
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-type: nlb    # To create Network Load Balancer
  # namespace: dev
spec:
  type: LoadBalancer # Default - Classic LB
  selector:
    app: usermgmt-restapp
  ports: 
    - port: 80
      targetPort: 8095
