apiVersion: v1
kind: Secret
metadata:
  name: private-repo-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: git@github.com:raghib1992/argocd-private-repo.git
  sshPrivateKey: |
    -----BEGIN OPENSSH PRIVATE KEY-----
    JQWOaC3ByZApIFfRRJnD6w48gOJTwMrvzvGixnCBMOFgf+cJlt4tjQFk0g6whnDZ9YxJRW
    ebyyrRK0dEwRcw4IdfLetaOe29uRjq01u20M+5n+44qK/z5rBD7pDCr4TwPiGw7tbrO3uj
    -----END OPENSSH PRIVATE KEY-----