apiVersion: v1
kind: Secret
metadata:
  name: private-repo-ssh
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: helm
  name: argo
  url: "https://argoproj.github.io/argo-helm"
  password: my-password
  username: my-username
  tlsClientCertData: ....
  tlsClientCertKey: ...