apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: creds-app
  namespace: argocd
spec: 
  destination: 
    namespace: creds-app
    server: "https://kubernetes.default.svc"
  project: default
  source: 
    path: guestbook
    repoURL: "https://github.com/raghib1992/argocd-private-repo.git"
    targetRevision: master
  syncPolicy:
    syncOptions:
      - CreateNamespace=true