apiVersion: argoproj.io/v1alpha1
kind: Application
metadata: 
  name: shaheenbook
  namespace: argocd
spec: 
  destination: 
    namespace: shaheen
    server: "https://kubernetes.default.svc"
  project: prod-project
  source: 
    path: helm-guestbook
    repoURL: "https://github.com/raghib1992/argocd-private-repo.git"
    targetRevision: master
    helm:
     releaseName: my-release
  syncPolicy:
    syncOptions:
      - CreateNamespace=true