apiVersion: v1
kind: Secret
metadata:
  name: private-repo-https
  namespace: argocd
  labels:
    argocd.argoproj.io/secret-type: repository
stringData:
  type: git
  url: "https://github.com/raghib1992/argocd-private-repo.git"
  password: ghp_JZ*************6m
  username: raghib1992