---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: deployment-role
  namespace: team-a
rules:
  - apiGroups:
      - ""
      - extensions
      - apps
    resources:
      - deployments
      - replicasets
      - pods
    verbs:
      - create
      - get
      - list
      - update
      - delete
      - watch
      - patch  
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: deployment-rolebinding
  namespace: team-a
roleRef:
  apiGroup: ""
  kind: Role
  name: deployment-role
subjects:
  - kind: Group
    name: Developers
    apiGroup: ""

