apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
spec:
  replicas: 3
  selector:
    matchLabels:
      component: server
  template:
    metadata:
      name: server-pod
      labels:
        component: server
    spec:
      containers:
        - name: server
          image: raghib1992/multi-server
          ports:
            - containerPort: 5000
          envFrom:
            - configMapRef:
                name: server-configmap2
          env:
            - name: PGPASSWORD
              valueFrom:
                secretKeyRef:
                  name: pgpassword
                  key: PGPASSWORD

          #   - name: REDIS_PORT
          #     valueFrom:
          #       configMapKeyRef:
          #         name: server-configmap
          #         key: redis_port
          #   - name: PGUSER
          #     valueFrom:
          #       configMapKeyRef:
          #         name: server-configmap
          #         key: pg_user
          #   - name: PGHOST
          #     valueFrom:
          #       configMapKeyRef:
          #         name: server-configmap
          #         value: pg_host
          #   - name: PGPORT
          #     valueFrom:
          #       configMapKeyRef:
          #         name: server-configmap
          #         value: pg_port
          #   - name: PGDATABASE
          #     valueFrom:
          #       configMapKeyRef:
          #         name: server-configmap
          #         value: pg_database
---
apiVersion: v1
kind: Service
metadata:
  name: server-clusterip
spec:
  type: ClusterIP
  selector:
    component: server
  ports:
    - targetPort: 5000
      port: 5000
# ---
# apiVersion: v1
# kind: ConfigMap
# metadata:
#   name: server-configmap
# data:
#   redis_host: redis-clusterip
#   redis_port: 6379
#   pg_user: postgres
#   pg_host: postgres-clusterip
#   pg_port: 5432
#   pg_database: postgres
