apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: mongo-ingress
  annotations:
    kubernetes.io/ingress.class: "nginx"
spec:
  rules:
  - host: kube.raghib.click
    http:
     paths:
     - path: "/"
       backend:
         service:
           name: webapp-service
           port:
             number: 3000