apiVersion: v1
kind: Pod
metadata:
  name: demopod-volume
spec:
  containers:
  - image: nginx
    name: test-container
    volumeMounts:
      - name: first-volume
        mountPath: /data
  volumes:
  - name: first-volume
    hostPath:
      path: /mydata
      type: Directory