apiVersion: v1
kind: ConfigMap
metadata:
  name: special-config-2
  namespace: default
data:
  special.how: very
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: env-config
  namespace: default
data:
  log_level: INFO